# -*- coding: utf-8 -*-
"""fashionApp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ke4FZvYF772EdEmNxpDCGpP3NzXQcHmw
"""

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_google_genai import GoogleGenerativeAI
from langchain.chains import LLMChain
from langchain.chains import SequentialChain
from langchain.prompts import PromptTemplate
import os
import google.generativeai as genai
from google.colab import userdata
import streamlit as st
import PIL.Image
from IPython.display import display, Image
import ipywidgets as widgets
import urllib.request
import requests
from io import BytesIO

# get the google_key
# googleKey = userdata.get('GOOGLE_API_KEY')
os.environ['GOOGLE_API_KEY']  = "AIzaSyAXYD2GdFjHGYHkQH7MTLovQzLWEYZAijU"


def fashion_idea(age, gender, pair, fabric, styling):

      # initialize the model for styling prompt
      model= ChatGoogleGenerativeAI(model = 'gemini-pro', temperature = 0.7)

      # Fashion Styling prompt
      prompt_style_temp = PromptTemplate(
          input_variables= ['age', 'gender', 'pair','fabric', 'styling'],
          template= "Act as a fashion designer, you have a {gender} client who are in there {age}'s, and you have to help them suggesting in the form of list  what will go with there {pair} of {fabric} to make a complete outfit for {styling} styling type"
      )

      style_chain = LLMChain(llm = model, prompt = prompt_style_temp, output_key = 'fashion_style')

      # initialize the model for fashion naming
      model  = ChatGoogleGenerativeAI(model="gemini-pro", temperature=0.7)

      # Naming your Fashion Style
      prompt_name_temp = PromptTemplate(
          input_variables = ['fashion_style'],
          template = "As a popular fashion designer you are supposed to name your style, the name that reminiscing the fashion style you suggested, which is {fashion_style}. Remember to keep name to be little simple to understand"
      )

      name_chain = LLMChain(llm = model, prompt= prompt_name_temp, output_key= 'fashion_name')

      chain = SequentialChain(
          chains= [style_chain, name_chain],
          input_variables = ['age', 'gender', 'pair','fabric', 'styling'],
          output_variables = ['fashion_style', 'fashion_name']
      )

      response = chain({'age': age, 'gender': gender, 'pair': pair, 'fabric': fabric, 'styling': styling})
      return response

# ============== Fashion Styling using the Uploaded Image or the Image from URL ===============
def fashion_idea_img(upld_img = None, url = None):
    if url :
      try:
          st.write("I'm in upload thing",url)
          # Fetch the image from the URL
          response = requests.get(url)

          # Ensure the request was successful
          response.raise_for_status()

          # Open the image from the response content
          img = PIL.Image.open(BytesIO(response.content))

      except requests.exceptions.RequestException as e:
          st.error(f"Failed to retrieve the image: {e}")

      #-------------Alternate Method-----------
      # urllib.request.urlretrieve(
      # url,
      # "img.jpg")

      # img = PIL.Image.open('img.jpg')

    else:
      img = PIL.Image.open(upld_img)

    st.image(img, caption="Fetched Image",width=300)

    # Prompt
    genai.configure(api_key= "AIzaSyAXYD2GdFjHGYHkQH7MTLovQzLWEYZAijU")
    model=genai.GenerativeModel("gemini-1.5-flash")
    prompt = """Act as a Fashion Designer, analyize the image of a dress and based on that suggest the complete remaining outfit, by giving multiple suggestions for each part of the remaining outfit that will go with it in the form of list, and also dont forget to name your design, the name that reminiscing the fashion style you suggested. Remember to keep name to be little simple to understand"""
    response=model.generate_content([prompt,img])

    return response.text.strip().split('\n')

def clear_text():
    st.session_state["input"] = ""
    st.session_state["input1"] = ""
    st.session_state["input2"] = ""
    st.session_state["input3"] = ""

st.title("Welcome to Your Personal Fashion Botique")

# Picker to upload the image or link for the dress
upld_img = st.sidebar.file_uploader("Upload an image", type = ["png", "jpg", "jpeg"])
st.sidebar.write("-------------------(OR)--------------------")
url_img = st.sidebar.text_input("Enter the image url link here", key="input3")

st.sidebar.write("-------------------(OR)--------------------")

# Picker to choose the inputs selection
age = st.sidebar.selectbox("What's Your Fashion Era? ",
                          ("👶Trendy Toddlers (0-5 years)", "🧒Stylish Sprouts (6-12 years)", "👦Chic Teens (13-19 years)", "👩Fashion-Forward Twenties (20-29 years)","👨Sartorial Thirties (30-39 years)","👩‍🦱 Fabulous Forties (40-49 years)","🧑‍🦳 Sensational Fifties (50-59 years)","🧓 Elegant Sixties and Beyond (60+ years)"), index = None)
gender = st.sidebar.selectbox("Whats your Fashion Persona?",("Female ","Male","🌟 Your fashion, your way—no label needed"), index= None)
pair = st.sidebar.text_input("What are trying to pair with?", key = "input")
fabric = gender = st.sidebar.text_input("What is the kind of fabric you are tring to pair with?", key = "input1")
styling = gender = st.sidebar.text_input("What is your prefered styling type(eg. Casual, Formal etc)?", key= "input2")


submit= st.sidebar.button("Click me", on_click=clear_text)

if submit:

    if upld_img is not None:
        wardrobe = fashion_idea_img(upld_img)
        # st.write("************* Wardrobe is wide open for you to choose **************")
        # for cloth in wardrobe:
        #   st.write(cloth)

    elif url_img:
      # st.write("I'm in else of url_img",url_img)
      wardrobe= fashion_idea_img(None, url_img)
      # st.write("************* Wardrobe is wide open for you to choose **************")
      # for cloth in wardrobe:
      #     st.write(cloth)


    else:
      print("Here")
      result = fashion_idea(age, gender, pair, fabric, styling)
      st.header(result['fashion_name'])

      wardrobe = result['fashion_style'].strip().split('\n')

    st.write("************* Wardrobe is wide open for you to choose **************")
    for cloth in wardrobe:
      st.write(cloth)


if __name__ == '__main__':
  print(upld_img)


# prompt_pair_temp.invoke({"age": "20", "gender": "female", "pair": "blue checks shirt", "fabric": "cotton", "styling": "formal"})